baseURL = "https://13ablo.github.io/my-devops-blog/"
title = "Genome"
theme = "archie"
languageCode = "en-us"
paginate = 5

[params]
  mode = "auto"              # auto dark/light mode
  subtitle = "DevOps thoughts, day by day"
  useCDN = false             # serve assets locally
  mathjax = false            # turn on if needed
  katex = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

# (Optional) Disqus
# disqusShortname = "yourDisqusShortname"
